### ISSUE TITLE
Cudatoolkit 11.8 

### ISSUE THREAD

**Issue by duxans** [DeepGraphLearning/ULTRA#7]
Hi,
I am looking forward to run ULTRA. Looking great!
 
I am actually stuck  installing the packages you refer in the installation instructions. I run the cuda installation (tried with pip also, and fixed the CUDA_HOME env variable as you pointed out) and got error with the cudatoolkit:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested cudatoolkit 11.8**
  - nothing provides cuda 11.8.* needed by pytorch-cuda-11.8-h8dd9ede_2

Could not solve for environment specs
The following packages are incompatible
├─ cudatoolkit 11.8**  does not exist (perhaps a typo or a missing channel);
└─ pytorch-cuda 11.8**  is not installable because it requires
   └─ cuda 11.8.* , which does not exist (perhaps a missing channel).
```
Do you know if another version of cudatoolkit runs well with your stack? Looks like the cudatoolkit 11.8 is giving (at least to me) some issues. I would appreciate any help.Thanks!
Jaime

**Comment by migalkin** [comment]
Hi, judging by the stack trace, you are using `mamba`, not conda, for env management - it might have different channels / package names / commands for installing cuda and cudatoolkit - I can't really help with that because we are not using mamba.

Generally, any cuda version compatible with recent PyTorch and PyG would work - afaik, PyTorch 2.0 supports 11.7 but then you might need to downgrade PyG. There should not be any major critical dependencies in the code on PyG 2.4, so it should work on older combinations of torch/pyg but I didn't test those.

**Comment by duxans** [comment]
Thanks @migalkin  for your quick response. I used conda for installing and don't know why a libmamba error is triggering. But I will take into account the info in your comment and keep on trying.
Thank you!
